# Generated by Django 2.2.2 on 2019-07-26 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RFCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hub.Device')),
            ],
        ),
        migrations.CreateModel(
            name='IRCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=100)),
                ('bits', models.IntegerField(default=0)),
                ('brand', models.CharField(max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hub.Device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='hub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hub.Hub'),
        ),
    ]
