# Generated by Django 2.2.2 on 2019-06-15 02:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_name', models.CharField(max_length=200)),
                ('action_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BooleanExpression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison_operator', models.CharField(choices=[('EQ', 0), ('NE', 1), ('GT', 2), ('LT', 3), ('GE', 4), ('LE', 5)], max_length=2)),
                ('constant_b', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PluginVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_name', models.CharField(max_length=200)),
                ('variable_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ConditionalStatement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('boolean_expressions_positions', models.CharField(max_length=200, validators=[django.core.validators.int_list_validator])),
                ('logical_operators', models.CharField(choices=[('OR', 0), ('AND', 1)], max_length=2)),
                ('logical_operators_positions', models.CharField(max_length=200, validators=[django.core.validators.int_list_validator])),
                ('open_paren_positions', models.CharField(max_length=100, validators=[django.core.validators.int_list_validator])),
                ('close_paren_positions', models.CharField(max_length=100, validators=[django.core.validators.int_list_validator])),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conditionals.Action')),
                ('boolean_expressions', models.ManyToManyField(to='conditionals.BooleanExpression')),
                ('reset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conditionals.ConditionalStatement')),
            ],
        ),
        migrations.AddField(
            model_name='booleanexpression',
            name='plugin_variable_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_variable_a', to='conditionals.PluginVariable'),
        ),
        migrations.AddField(
            model_name='booleanexpression',
            name='plugin_variable_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_variable_b', to='conditionals.PluginVariable'),
        ),
    ]
