# Generated by Django 2.2.2 on 2019-06-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conditionals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booleanexpression',
            name='comparison_operator',
            field=models.CharField(choices=[('EQ', 'EQ'), ('NE', 'NE'), ('GT', 'GT'), ('LT', 'LT'), ('GE', 'GE'), ('LE', 'LE')], max_length=2),
        ),
        migrations.AlterField(
            model_name='conditionalstatement',
            name='logical_operators',
            field=models.CharField(choices=[('OR', 'OR'), ('AND', 'AND')], max_length=2),
        ),
    ]
